#!/usr/bin/env bash

set -e

reponame=$(basename $PWD | awk '{print tolower($0)}')
arch=$(arch)

imagename="hybird/$arch/$reponame-dep:latest"
docker build -f ~lou/loam_workspace/loam_velodyne/Dependencies -t $imagename .